/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.simulador.plugin.biblioteca.componentes;

import javax.swing.AbstractButton;

/**
 *
 * @author Douglas
 */
public class Interruptor extends javax.swing.JPanel {

    /**
     * Creates new form Interruptor
     */
    public Interruptor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInterruptor = new javax.swing.JPanel();
        btnInterruptor = new javax.swing.JToggleButton();

        pnlInterruptor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)), "Interruptor"));
        pnlInterruptor.setPreferredSize(new java.awt.Dimension(175, 61));

        btnInterruptor.setText("OFF");
        btnInterruptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInterruptorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInterruptorLayout = new javax.swing.GroupLayout(pnlInterruptor);
        pnlInterruptor.setLayout(pnlInterruptorLayout);
        pnlInterruptorLayout.setHorizontalGroup(
            pnlInterruptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInterruptorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInterruptor, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlInterruptorLayout.setVerticalGroup(
            pnlInterruptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInterruptorLayout.createSequentialGroup()
                .addComponent(btnInterruptor)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInterruptor, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInterruptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnInterruptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterruptorActionPerformed
        AbstractButton abstractButton = (AbstractButton) evt.getSource();
        boolean selected = abstractButton.getModel().isSelected();
        
        if(selected)
            btnInterruptor.setText("ON");
        else
            btnInterruptor.setText("OFF");
        
        btnInterruptor.setSelected(selected);
        
    }//GEN-LAST:event_btnInterruptorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnInterruptor;
    private javax.swing.JPanel pnlInterruptor;
    // End of variables declaration//GEN-END:variables
}
